sudo: false
dist: trusty
language: node_js
node_js:
- '10'
before_install:
- if [[ `npm -v` != 6* ]]; then npm install --unsafe-perm --verbose -g npm@6; fi
install:
- npm install
script:
- eslint src
- wct --configFile saucelabs.conf.json --plugin sauce
notifications:
  email: false
addons:
  sauce_connect: true
